version: "3.8"

services:

  pa-camellar: 
    container_name: front
    build: 
      context: .
      dockerfile: Dockerfile
    image: front:v1
    ports:
      - 80:80
    networks:
     - internalnet

networks:
  internalnet:
    driver: bridge